### ISSUE TITLE
Include "receive file" feature in KwikAPI

### ISSUE THREAD

**Issue by Venkatesh-283** [deep-compute/kwikapi#104]
Hi Team,
In KwikAPI there is no support to receive a file as input and process it. Can you please include this feature?

CC: @RamanjaneyuluIdavalapati @venugopalkandru

**Comment by sundarrajan78** [comment]
@ManishaBayya @jaswanth098 Can you please have a look at this issue?

**Comment by jaswanth098** [comment]
as per [this comment](https://github.com/deep-compute/kwikapi/pull/105#issuecomment-600783403) we shall not support this
