### ISSUE TITLE
Support type checking in KwikAPI

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/kwikapi#27]
Links to refer
- https://medium.com/@ageitgey/learn-how-to-use-static-type-checking-in-python-3-6-in-10-minutes-12c86d72677b
- https://pypi.python.org/pypi/typecheck-decorator

**Comment by jaswanth098** [comment]
As we are not working on kwikapi moving this to ready

**Comment by jaswanth098** [comment]
Not working actively on this issue, moving this to ready-status

**Comment by jaswanth098** [comment]
This is already implemented but disabled will come back to this later

**Comment by jaswanth098** [comment]
did not get time to look into this
