### ISSUE TITLE
KwikAPI bug

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/kwikapi#33]
Why 'if request.fn_params' is doing in request handler.

**Comment by jaswanth098** [comment]
@RamanjaneyuluIdavalapati what is this issue exactly about

**Comment by IdavalapatiRamanjaneyulu** [comment]
@jaswanth098 This issue is not relevant now. We can close this.

**Comment by jaswanth098** [comment]
thanks closing this
