### ISSUE TITLE
#Error: kwikapi Client issue.

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#41]
@RamanjaneyuluIdavalapati 
* While using `kwikapi client` I am facing an issue can you please check once and let me know.
#### Error:
![screen shot 2018-05-15 at 11 11 52 am](https://user-images.githubusercontent.com/16955073/40038687-0f723364-5831-11e8-9995-912734027fb4.png)

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R 
- The variable is not required and we removed it. It will work now.
