### ISSUE TITLE
#Bug: Datatype `Any` return generator object.

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#42]
@RamanjaneyuluIdavalapati 
* While sending a data type of class object through `kwickapi` argument I specified the type as `Any` in the api function for that reason i got `generator` object instead of class object.
#### Api function.
![screen shot 2018-05-15 at 7 47 14 pm](https://user-images.githubusercontent.com/16955073/40062439-d9353d44-5878-11e8-9c05-d34193727205.png)
#### Making request.
![screen shot 2018-05-15 at 7 40 30 pm](https://user-images.githubusercontent.com/16955073/40062357-ab7e3374-5878-11e8-9b94-69fb2a7a6cdd.png)
#### Receiving request.
![screen shot 2018-05-15 at 7 42 03 pm](https://user-images.githubusercontent.com/16955073/40062383-b8b3b74e-5878-11e8-8ec0-9ccbba21b351.png)

**Comment by ghost** [comment]
@RamanjaneyuluIdavalapati 
* In python3 while using the `msgpack` with class object after unpack it modified the data type you can see below. Because of this issue while sending the class object through `kwikapi` we are receiving `generator` at server side.
![screen shot 2018-05-15 at 7 33 25 pm](https://user-images.githubusercontent.com/16955073/40061935-abba5224-5877-11e8-9e71-fb168ae24745.png)

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R 
- The generator problem is solved. 
- And about your second issue, as of now kwikapi doesn't support sending class objects from client to server or vice versa.
