### ISSUE TITLE
#Bug: Msgpack byte issue in python3.

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#43]
@RamanjaneyuluIdavalapati 
* While doing the api request using `kwikapi` we are sending function arguments as `string` but in api function it receives as `byte` instead of `string` because in `python3` msgpack make it as a `byte`.
![screen shot 2018-05-15 at 7 57 05 pm](https://user-images.githubusercontent.com/16955073/40063101-32ee6b84-587a-11e8-8a0f-879c27b2dc97.png)
#### python2.7
![screen shot 2018-05-15 at 8 05 16 pm](https://user-images.githubusercontent.com/16955073/40063621-635b05c4-587b-11e8-8c8c-ee286d29c660.png)
#### python3
![screen shot 2018-05-15 at 8 04 08 pm](https://user-images.githubusercontent.com/16955073/40063635-6a82677a-587b-11e8-806f-b6f1f145a77f.png)

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R 
- This is because the msgpack is using utf-8 for encoding by default. But while unpacking it is not decoding until unless we explicitly specify it.

- Ex: msgpack.unpackb(msgpack.packb('blah'), encoding='utf-8')

- This is solved in the latest commit.
