### ISSUE TITLE
#Error: UnboundLocalError in kwikapi client. 

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#49]
#### Read-Me:
* While using `kwikapi` we are getting an error inside the client code and check the error given below.
#### Error:
![screen shot 2018-06-06 at 3 05 16 pm](https://user-images.githubusercontent.com/16955073/41030275-9637cb54-699b-11e8-947d-4ca67f800095.png)

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R 

- We used wrong variable name(typo) in this.
- This is solved, so I am closing this.
