### ISSUE TITLE
#Error: RuntimeError in kwikapi.tornado

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#50]
#### Read-Me:
* While doing request using `kwikapi.tornado` we are getting an error but still, we are getting a response.
#### Error:
![33754313_394678024380176_7264013926424117248_n](https://user-images.githubusercontent.com/16955073/41030520-25a8419c-699c-11e8-87e8-5e0ae1b42e77.png)

**Comment by IdavalapatiRamanjaneyulu** [comment]
@Rajendra-R 
- The bug is fixed in the latest commit. You can install the latest version to overcome this error.
