### ISSUE TITLE
#Error: Msgpack error in kwikapi client.

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#54]
@RamanjaneyuluIdavalapati 
#### Read-Me:
* I Wrote an API function using kwikapi which returns `generator` and I am requesting the API using kwikapi client I am getting an error.
#### Error:
![screen shot 2018-06-14 at 10 04 55 am](https://user-images.githubusercontent.com/16955073/41391911-08728ba8-6fbb-11e8-8875-fb03301b31f8.png)

**Comment by jaswanth098** [comment]
As we are not working on kwikapi moving this to ready

**Comment by jaswanth098** [comment]
not working on this actively moving this to ready
