### ISSUE TITLE
Streaming not working as expected

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi#61]
@RamanjaneyuluIdavalapati 
- As per the documentation created two API's(streaming documentation) While requesting those API's with 5GB input file. Instead of streaming it is loading data in ram
- Can you once check and fix this ASAP.

**Comment by kumar550** [comment]
@RamanjaneyuluIdavalapati 
- Can you please increase priority for this ticket

**Comment by jaswanth098** [comment]
Not working on this moving this to ready-status

**Comment by jaswanth098** [comment]
Not working on this moving to ready-status
