### ISSUE TITLE
Unable to access log object in constructor(__init__) in API building class

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi#62]
@RamanjaneyuluIdavalapati This is my script
```python
import tornado.ioloop
import tornado.web

from kwikapi.tornado import RequestHandler
from kwikapi import API

from basescript import BaseScript

# Core logic that you want to expose as a service
class Calc(object):
    def __init__(self):
        self.log.info('Am Calc class')

    def add(self, a: int, b: int) -> int:
        self.log.info('ADD API got a request')
        return a + b

    def subtract(self, a: int, b: int) -> int:
        return a - b

# Standard boilerplate code to define the service. This
# code will remain more or less the same size regardless
# of how big the code/complexity of `BaseCalc` above is.

class Test(BaseScript):

    def run(self):
        super(Test, self).run()

        # Register BaseCalc with KwikAPI
        api = API(log=self.log)
        api.register(Calc(), 'v1')

        # Passing RequestHandler to the KwikAPI
        app = tornado.web.Application([
                (r'^/api/.*', RequestHandler, dict(api=api)),
            ])
        app.listen(8889)
        tornado.ioloop.IOLoop.current().start()

# Starting the application
if __name__ == "__main__":
    Test().start()
```

- In the constructor, I am not able to use the log object?
- Can you check and fix it ASAP

- In the meantime, I will fix in another way by sending a log object while creating the class object.

**Comment by kumar550** [comment]
@RamanjaneyuluIdavalapati 
- While registering with `api` object, we are creating an object for `Calc` class. At that time there is no `log` attribute or function in that class. (due to this it is raising an error)

- After `Calc` class object registered, we are assigning `log` attribute to `Calc` object.

**Comment by jaswanth098** [comment]
Will be checking this problem in a while

**Comment by jaswanth098** [comment]
This is a problem with the initialization above if a user wants something in the class that he defined user has to pass to it kwikapi cannot do anything because kwikapi only takes an instance of a class but not a class definition,
closing this as we don't need to do anything in this
