### ISSUE TITLE
Generator class name is missing in return type

### ISSUE THREAD

**Issue by kumar550** [deep-compute/kwikapi#64]
@RamanjaneyuluIdavalapati 
- While returning data types of function attributes, for `typing datatypes` instead of datatype we are getting the string object

ex: 
`return_type: "typing.Generator<+T_co, -T_contra, +V_co>"`
expecting:
`return_type: "Generator"`

**Comment by kumar550** [comment]
@RamanjaneyuluIdavalapati 
- As you fixed this in latest version `0.4.2` => closing this

**Comment by IdavalapatiRamanjaneyulu** [comment]
@kumar550  
I am not. You only fixed it.
