### ISSUE TITLE
#Error: Generator API response error. 

### ISSUE THREAD

**Issue by ghost** [deep-compute/kwikapi#67]
@RamanjaneyuluIdavalapati 
* In Kwikapi if a function is returning generator while processing the API function we got an error that error you have to show as an API response instead of that we are getting an error.
![screen shot 2018-08-27 at 6 15 10 pm](https://user-images.githubusercontent.com/16955073/44660542-8663cf00-aa25-11e8-9af3-0ca440aa1c4c.png)

**Comment by jaswanth098** [comment]
Not working on this repo actively moving this to ready-status for now
