### ISSUE TITLE
Request for Edit access just keeps spinning

### ISSUE THREAD

**Issue by prashanthellina** [deep-compute/kwikapi#87]
https://kwikui.com/view/c5bf4a#view

![Screenshot from 2019-04-25 09-42-40](https://user-images.githubusercontent.com/3989/56740231-8c3dbb80-673e-11e9-9275-f79dcdead450.png)

**Comment by prashanthellina** [comment]
Spinning stopped now after many seconds.

**Comment by prashanthellina** [comment]
Need visual marker here (a tick mark or something)

**Comment by jaswanth098** [comment]
got it will work towards it

**Comment by jaswanth098** [comment]
@prashanthellina This is wrong repo will be tracking this in https://github.com/deep-compute/kwikui/issues/1127

**Comment by prashanthellina** [comment]
oh! my bad. thank you.
