### ISSUE TITLE
Supporting ProcessPoolExecutor.

### ISSUE THREAD

**Issue by IdavalapatiRamanjaneyulu** [deep-compute/kwikapi#96]
KwikAPI supports taking threadpool. If not given it uses `ThreadPoolExecutor`. But as we know this uses only one core, the server is not picking up my request quickly when the other request is processing(when it uses 100% CPU core). There may be chances of timing out the request. If we support taking `ProcessPoolExecutor` so that if one core is busy the request will be processed on the other CPU core.

**Note:** We need README for this (at least for threadpool).

**Comment by jaswanth098** [comment]
@RamanjaneyuluIdavalapati Please take this up when you can, Right now I will not be able to take this up

**Comment by IdavalapatiRamanjaneyulu** [comment]
@jaswanth098 Sure.

**Comment by jaswanth098** [comment]
not important
